# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    ignore:
      # Ignore all patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      # Ignore specific dependencies for major  updates
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vitest'
        update-types: ['version-update:semver-major']
      - dependency-name: '@vitest/coverage-v8'
        update-types: ['version-update:semver-major']
      - dependency-name: '@typescript-eslint/*'
        update-types: ['version-update:semver-major']
